[project]
name = "erpnext"
authors = [
    { name = "Frappe Technologies Pvt Ltd", email = "developers@frappe.io"}
]
description = "Open Source ERP"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # Core dependencies
    "python-stdnum~=1.16",
    "Unidecode~=1.2.0",

    # integration dependencies
    "gocardless-pro~=1.22.0",
    "googlemaps",
    "plaid-python~=7.2.1",
    "taxjar~=1.9.2",
    "WooCommerce==2.1.1",
    "PyGithub==1.44.1",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 99

[tool.isort]
line_length = 99
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
indent = "\t"